### ISSUE TITLE
Can't compile with Erlang 20.1

### ISSUE THREAD

**Issue by dbernheisel** [thoughtbot/bamboo#320]
I'm not positive it's because of Erlang 20.1, however this issue started happening when I bumped a project to use Erlang 20.1 (which I need since I'm on macOS High Sierra).

```
== Compilation error in file web/email/to_customer.ex ==
** (CompileError) web/email/to_customer.ex:2: module Bamboo.Phoenix is not loaded and could not be found
    (elixir) expanding macro: Kernel.use/2
    web/email/to_customer.ex:2: MyApp.Email.ToCustomer (module)
    (elixir) lib/kernel/parallel_compiler.ex:121: anonymous fn/4 in Kernel.ParallelCompiler.spawn_compilers/1
```

raised from this line: `use Bamboo.Phoenix, view: MyApp.Email.ToCustomerView`

When I reverted back to using this commit: https://github.com/thoughtbot/bamboo/commit/69d7582ab3dd9973b57f10271328a79bd377b314 it worked fine, so I suspect it has something to do with `Bamboo.Phoenix` being conditionally declared from this PR: https://github.com/thoughtbot/bamboo/pull/304

**Comment by voger** [comment]
I just had the same problem . Deleted the conditional and it compiled.

**Comment by technicalcapt** [comment]
@kelvinst Getting the same error. Do you have a fix for this issue?

**Comment by kelvinst** [comment]
Well, I had some issues with Erlang 20 upgrade and docker, don't know if it's the same reason but give a check at the elixir forum thread: https://elixirforum.com/t/error-loading-module-poolboy-inside-a-docker-container/6611

**Comment by rickclare** [comment]
We are experiencing the same issue (using Erlang v20.1.4 and Elixir 1.5.2).  Previous compile was working with Bamboo v1.0.0-rc.1,  but has starting failing in v1.0.0-rc.2

Firstly found it difficult to recreate in dev (was failing in our docker builds), but a fully clean in our dev environment reproduced the issue:

```
$ mix deps.clean --all && mix deps.get && mix compile
...
...
== Compilation error in file lib/my_app_web/email/base_email.ex ==
** (CompileError) lib/my_app_web/email/base_email.ex:3: module Bamboo.Phoenix is not loaded and could not be found
    (stdlib) lists.erl:1354: :lists.mapfoldl/3
    (stdlib) lists.erl:1355: :lists.mapfoldl/3
    (stdlib) erl_eval.erl:670: :erl_eval.do_apply/6
    (elixir) lib/kernel/parallel_compiler.ex:121: anonymous fn/4 in Kernel.ParallelCompiler.spawn_compilers/1
```

Was able to "solve" the issue, by compiling phoenix first, then compiling the rest of the project:

```
mix deps.compile phoenix --include-children && mix compile
...
...
==> my_app
Compiling 159 files (.ex)
Generated my_app app
```

Obviously this isn't a long term solution (ideally we should only need to run `mix compile` only)

I'm not aware of any way to specify a compile order in `mix.exs` (even that even is the right approach to this?). Anyone have any ideas?

**Comment by danschultzer** [comment]
This breaks our setup too. Phoenix isn't compiled before Bamboo, but the tests run successfully in this repo as Bamboo will always be compiled last. It seems that bamboo is broken on all Phoenix installations.

I suggest that the `Code.ensure_loaded?` conditional is removed. To fix the issues in #187, either other parts in `Bamboo.Phoenix` should be refactored, or the whole thing should just be moved it to its own library as previously discussed.

BTW the #304 PR also made this method pointless (it'll never be called): https://github.com/thoughtbot/bamboo/blob/945fff96570d4fdfa83082eaf8fdfe7a21599aef/lib/bamboo/phoenix.ex#L132-L137

The `bamboo_phoenix` library is probably the best approach, so there's no need to think about or test for compile issues.

wdyt @kelvinst @paulcsmith?

**Comment by paulcsmith** [comment]
@danschultzer I think extracting a `bamboo_phoenix` lib is the best long term choice, but I'd love to get this fixed asap too. If you have a moment could you remove the outer `Code.ensure_loaded?(:phoenix)` to see if that fixes the issues. I'd rather have compile warnings than not having it compile at all :S

Then later on we can extract a bamboo_phoenix lib

**Comment by danschultzer** [comment]
@paulcsmith I've submitted the PR 🚀

**Comment by paulcsmith** [comment]
Going to close this and open an issue about extracting a `bamboo_phoenix` lib
