### PR TITLE
Ensure that Bamboo.Phoenix gets compiled

### LINKED ISSUE #320: Can't compile with Erlang 20.1
I'm not positive it's because of Erlang 20.1, however this issue started happening when I bumped a project to use Erlang 20.1 (which I need since I'm on macOS High Sierra).

```
== Compilation error in file web/email/to_customer.ex ==
** (CompileError) web/email/to_customer.ex:2: module Bamboo.Phoenix is not loaded and could not be found
    (elixir) expanding macro: Kernel.use/2
    web/email/to_customer.ex:2: MyApp.Email.ToCustomer (module)
    (elixir) lib/kernel/parallel_compiler.ex:121: anonymous fn/4 in Kernel.ParallelCompiler.spawn_compilers/1
```

raised from this line: `use Bamboo.Phoenix, view: MyApp.Email.ToCustomerView`

When I reverted back to using this commit: https://github.com/thoughtbot/bamboo/commit/69d7582ab3dd9973b57f10271328a79bd377b314 it worked fine, so I suspect it has something to do with `Bamboo.Phoenix` being conditionally declared from this PR: https://github.com/thoughtbot/bamboo/pull/304

### PR DESCRIPTION
**Pull request by danschultzer**
This reverts the change in #304 that caused `Bamboo.Phoenix` to never be compiled in Phoenix installations.

I've tested this on my Phoenix app with `mix deps.clean --all; mix deps.get; mix test`, and it no longer fails with `Bamboo.Phoenix` `CompileError` 👍 

Resolves #320

### CODE REVIEW

**Comment by paulcsmith** [comment]
Closed and reopened so it runs in CI. Once it passes I'll merge it in. Thanks for doing this!

**Comment by johnhamelink** [comment]
Has a release with this PR in it made its way to hex yet?

**Comment by hisapy** [comment]
Hi guys,

Is there an estimated release date for this changes ?

Thanks in advance

**Comment by williamweckl** [comment]
Still waiting for a release with this fix.

**Comment by paulcsmith** [comment]
New rc3 published to hex!
